name: ScoreKeeper
main: com.majinnaibu.minecraft.plugins.scorekeeper.ScoreKeeperPlugin
version: 0.1.0
api-version: 1.21
commands:
    score-get:
        description: Displays the player's score.
        usage: /score-get [playername]
    score-add:
        description: Adds point to the player's score.
        usage: /score-add [playername] <amount>
    score-subtract:
        description: Subtracts points from the player's score.
        usage: /score-subtract [playername] <amount>
    score-reset: 
        description: Resets the player's score
        usage: /score-reset [playername]
    score-archive:
        description: Archives and resets the player's score 
        usage: /score-archive [playername]
        